apiVersion: v1
kind: Service
metadata:
  labels:
    role: svc-pod-app-webapp
  name: svc-pod-app-webapp
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    instance: pod-app-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-app-webapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      instance: pod-app-webapp
  template:
    metadata:
      labels:
        instance: pod-app-webapp
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: instance
                      operator: In
                      values:
                        - pod-app-webapp
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "200Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
